Repository PicnicSupermarket/error-prone-support, pull requests merged in 2022-11, with the labels that each got.

#331 Configure documentation URL for `StringJoin` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java
Labels: documentation

#333 add Reproducible Builds badge
  README.md
Labels: documentation

#323 Introduce `IsInstanceLambdaUsage` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IsInstanceLambdaUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MethodReferenceUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/IsInstanceLambdaUsageTest.java
Labels: new feature

#322 Introduce Refaster rules to streamline `java.time` type creation
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TimeRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TimeRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TimeRulesTestOutput.java
Labels: new feature

#327 Introduce `Optional{Filter,Map}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java
Labels: new feature

#339 Introduce `MapIsEmpty` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MapRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MapRulesTestOutput.java
Labels: new feature

#357 Have Renovate file `ruby/setup-ruby` upgrade PRs at most once a month
  .renovaterc.json
Labels: chore

#358 Extend `MonoFlux` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#347 Improve `Tree` deletion suggestions
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AutowiredConstructor.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/EmptyMethod.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/SourceCode.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/AutowiredConstructorTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/EmptyMethodTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/SourceCodeTest.java
Labels: improvement

#335 Introduce `More{ASTHelpers,JUnitMatchers,Matchers}` utility classes
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitMethodDeclaration.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreASTHelpers.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreJUnitMatchers.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreMatchers.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreASTHelpersTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreJUnitMatchersTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreMatchersTest.java
Labels: improvement

#370 Introduce `{Mono,Flux}DefaultIfEmpty` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#374 Introduce some Refaster rules that avoid nested `Publisher`s
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#346 Report mutation test coverage of proposed changes
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
  README.md
  cdg-pitest-licence.txt
  pom.xml
Labels: chore
