Repository PicnicSupermarket/error-prone-support, pull requests merged in 2022-12, with the labels that each got.

#214 Introduce `JUnitClassModifiers` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitClassModifiers.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/JUnitClassModifiersTest.java
Labels: new feature

#383 Improve mutation testing setup
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreTypesTest.java
  pom.xml
Labels: chore

#376 Introduce `StringCaseLocaleUsage` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringCaseLocaleUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StringCaseLocaleUsageTest.java
Labels: new feature

#392 Downgrade actions/setup-java v3.7.0 -> v3.6.0
  .github/workflows/build.yaml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
Labels: chore

#385 Introduce `Mono{Empty,Just,JustOrEmpty}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#384 Introduce `MonoFromOptionalSwitchIfEmpty` and `OptionalMapMonoJust` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#390 Introduce `CollectionForEach` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Labels: new feature

#394 Prefer `BigDecimal.valueOf(double)` over `new BigDecimal(double)`
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/BigDecimalRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BigDecimalRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BigDecimalRulesTestOutput.java
Labels: new feature

#397 Prevent `ReverseOrder` Refaster rule from introducing a static import
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java
Labels: bug

#403 Drop indentation in feature request issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#401 Improve `IsInstanceLambdaUsage` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IsInstanceLambdaUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/IsInstanceLambdaUsageTest.java
Labels: bug fix

#400 Fix suggestions emitted by the `StringCaseLocaleUsage` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringCaseLocaleUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StringCaseLocaleUsageTest.java
  pom.xml
Labels: bug fix

#404 Show Christmas Cody in README and on website home page
  website/assets/images/logo-dark.svg
  website/assets/images/logo.svg
Labels: documentation

#405 Introduce `MonoIdentity` and `MonoThen` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#410 Upgrade Error Prone fork v2.16-picnic-1 -> v2.16-picnic-2
  pom.xml
Labels: dependencies

#412 Prevent `NestedOptionals` from throwing an NPE
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NestedOptionals.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/NestedOptionalsTest.java
Labels: bug fix

#407 Improve `IdentityConversion` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/IdentityConversionTest.java
Labels: bug fix

#406 Improve `JUnitMethodDeclaration` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitMethodDeclaration.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/JavaKeywords.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/JUnitMethodDeclarationTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/JavaKeywordsTest.java
Labels: bug fix

#408 Update website styling and add Google site verification
  website/README.md
  website/_config.yml
  website/_includes/footer_custom.html
  website/_includes/head_custom.html
  website/_sass/color_schemes/_common.scss
  website/_sass/color_schemes/_variables.scss
  website/_sass/color_schemes/eps-dark.scss
Labels: documentation
