Repository PicnicSupermarket/error-prone-support, pull requests merged in 2022-10, with the labels that each got.

#251 Update `BugPattern#{link,linkType.CUSTOM}` to link to our website
  README.md
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AmbiguousJsonCreator.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AssertJIsNull.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AutowiredConstructor.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalAnnotationSyntax.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CollectorMutability.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/EmptyMethod.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ErrorProneTestHelperSourceFormat.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrdering.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ImmutablesSortedSetComparator.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitMethodDeclaration.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MethodReferenceUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MissingRefasterAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MockitoStubbing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NestedOptionals.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonEmptyMono.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/PrimitiveComparison.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RefasterAnyOfUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RefasterTemplateModifiers.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestMappingAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestParamType.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ScheduledTransactionTrace.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatement.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/SpringMvcAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/Documentation.java
Labels: new feature

#253 Set up documentation website generation and deployment
  .github/workflows/build.yaml
  .github/workflows/deploy-website.yaml
  README.md
  generate-docs.sh
  website/.gitignore
  website/404.md
  website/Gemfile
  website/README.md
  website/_config.yml
  website/_includes/footer_custom.html
  website/_includes/head_custom.html
  website/_sass/custom/custom.scss
  website/assets/images/android-chrome-192x192.png
  website/assets/images/android-chrome-512x512.png
  website/assets/images/apple-touch-icon.png
  website/assets/images/browserconfig.xml
  website/assets/images/favicon-16x16.png
  website/assets/images/favicon-32x32.png
  website/assets/images/favicon.svg
  website/assets/images/logo-dark.svg
  website/assets/images/logo.svg
  website/assets/images/mstile-150x150.png
  website/assets/images/picnic-logo@2x.png
  website/assets/images/safari-pinned-tab.svg
  website/assets/images/site.webmanifest
  website/bugpatterns.md
  website/favicon.ico
  website/refastertemplates.md
Labels: new feature

#278 Fix default branch reference in GitHub Actions definition
  .github/workflows/build.yaml
  .github/workflows/deploy-website.yaml
Labels: chore

#194 Introduce `StringJoin` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrdering.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatement.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StringJoinTest.java
Labels: new feature

#273 Introduce `{Mono,Flux}OnErrorComplete` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refastertemplates/ReactorTemplates.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refastertemplates/ReactorTemplatesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refastertemplates/ReactorTemplatesTestOutput.java
Labels: new feature

#281 Fix `LexicographicalAnnotationAttributeListing` string sorting
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListingTest.java
Labels: bug fix

#282 Reference blog post in README
  README.md
Labels: documentation

#279 Prefer `flatMapIterable(identity())` over `flatMap(i -> FluxfromIterable(i))`
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refastertemplates/ReactorTemplates.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refastertemplates/ReactorTemplatesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refastertemplates/ReactorTemplatesTestOutput.java
Labels: new feature

#285 Have website use theme variables instead of custom SASS overrides
  website/_includes/head_custom.html
  website/_sass/color_schemes/_common.scss
  website/_sass/color_schemes/_variables.scss
  website/_sass/color_schemes/eps-dark.scss
  website/_sass/color_schemes/eps-light.scss
  website/_sass/custom/custom.scss
  website/assets/css/just-the-docs-eps-dark.scss
  website/assets/css/just-the-docs-eps-light.scss
Labels: chore

#274 Unify local and GitHub Actions website generation flow
  .github/workflows/deploy-website.yaml
  generate-docs.sh
  website/.ruby-version
  website/Gemfile
  website/README.md
  website/_config.yml
Labels: chore

#287 Accommodate rapid website development on the `website` branch
  .github/workflows/deploy-website.yaml
Labels: chore

#289 Rename `Slf4JLogStatementTest` to `Slf4jLogStatementTest`
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatementTest.java
Labels: improvement

#304 Make the build JDK 18+ compatible
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AmbiguousJsonCreator.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AssertJIsNull.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AutowiredConstructor.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalAnnotationSyntax.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CollectorMutability.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/EmptyMethod.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ErrorProneTestHelperSourceFormat.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrdering.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ImmutablesSortedSetComparator.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitMethodDeclaration.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MethodReferenceUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MissingRefasterAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MockitoStubbing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NestedOptionals.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonEmptyMono.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/PrimitiveComparison.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RefasterAnyOfUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RefasterRuleModifiers.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestMappingAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestParamType.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ScheduledTransactionTrace.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatement.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/SpringMvcAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MethodMatcherFactory.java
  refaster-compiler/src/main/java/tech/picnic/errorprone/refaster/plugin/RefasterRuleCompiler.java
  refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/AnnotatedCompositeCodeTransformer.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsArray.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsCharacter.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/ThrowsCheckedException.java
Labels: improvement

#310 Don't update `project.build.outputTimestamp` on `mvn versions:set`
  pom.xml
Labels: chore

#182 Have `LexicographicalAnnotationListing` sort `TYPE_USE` annotations last
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationListing.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationListingTest.java
Labels: improvement

#181 Migrate from JSR 305 to JSpecify
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/package-info.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/package-info.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssortedRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MultimapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/NullRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/package-info.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RequestParamTypeTest.java
  pom.xml
  refaster-compiler/pom.xml
  refaster-compiler/src/main/java/tech/picnic/errorprone/refaster/plugin/RefasterRuleCompilerTaskListener.java
  refaster-compiler/src/main/java/tech/picnic/errorprone/refaster/plugin/package-info.java
  refaster-runner/pom.xml
  refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/package-info.java
  refaster-support/pom.xml
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/annotation/package-info.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/package-info.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/package-info.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/AbstractMatcherTestChecker.java
  refaster-test-support/pom.xml
  refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/RefasterRuleCollection.java
  refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/package-info.java
  refaster-test-support/src/test/java/tech/picnic/errorprone/refaster/test/ValidRules.java
Labels: improvement

#311 Introduce additional matchers to `TimeZoneUsage` rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsageTest.java
Labels: improvement

#301 Run build workflow for non-LTS JDKs
  .github/workflows/build.yaml
Labels: chore

#314 Prefer `Flux#take(long, boolean)` over `Flux#take(long)` to limit upstream generation
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#224 Have `FluxFlatMapUsage` better handle nested `Publisher`s
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsageTest.java
Labels: improvement

#293 Introduce `{Mono,Flux}#zipWith{,Iterable}` Refaster rules
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#142 Introduce `{Mono,Flux}Map{,NotNull}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#284 Improve build and deployment concurrency handling
  .github/workflows/deploy-website.yaml
Labels: chore

#308 By default, prevent `BugChecker`s from introducing new dependencies
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CollectorMutability.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ScheduledTransactionTrace.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibrary.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/CollectorMutabilityTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ScheduledTransactionTraceTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibraryTest.java
Labels: improvement

#318 Introduce assorted Reactor error handling Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature
