Repository PicnicSupermarket/error-prone-support, pull requests merged in 2023-03, with the labels that each got.

#516 Introduce `FluxCountMapMathToIntExact` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#188 Introduce `JUnitValueSource` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitValueSource.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreJUnitMatchers.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/JUnitValueSourceTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreJUnitMatchersTest.java
Labels: new feature

#517 Introduce `ImmutableMapCopyOfMapsFilter{Keys,Values}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMapRulesTestOutput.java
Labels: new feature

#454 Introduce `MockitoMockClassReference` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MockitoMockClassReference.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/MockitoMockClassReferenceTest.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/AnnotatedCompositeCodeTransformerTest.java
Labels: new feature

#521 Upgrade JDKs used by GitHub Actions builds
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yaml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/SourceCodeTest.java
  pom.xml
Labels: dependencies

#530 Introduce `AssertThatPathContent{,Utf8}` Refaster rules
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/BugPatternExtractorTest.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJStringRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestOutput.java
Labels: new feature

#543 Extend set of parameter types recognized by `RequestMappingAnnotation`
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestMappingAnnotation.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RequestMappingAnnotationTest.java
Labels: improvement

#541 Extend `StepVerifierStepIdentity` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#523 Extend `null` check Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/NullRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PreconditionsRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PreconditionsRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PreconditionsRulesTestOutput.java
Labels: new feature

#513 Introduce `DirectReturn` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/DirectReturn.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MockitoMockClassReference.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreASTHelpers.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/DirectReturnTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreASTHelpersTest.java
Labels: new feature
