Repository PicnicSupermarket/error-prone-support, pull requests merged in 2023-12, with the labels that each got.

#923 Show Christmas Cody in README and on website home page
  website/assets/images/logo-dark.svg
  website/assets/images/logo.svg
Labels: documentation

#910 StaticImport: add various `com.fasterxml.jackson.annotation` values
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StaticImportTest.java
Labels: improvement

#926 Skip SonarCloud analysis of PRs from forked repositories
  .github/workflows/sonarcloud.yml
Labels: chore

#881 Introduce `CanonicalClassNameUsage` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalClassNameUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/DirectReturn.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrdering.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxImplicitBlock.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitValueSource.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MockitoMockClassReference.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonEmptyMono.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/PrimitiveComparison.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RefasterAnyOfUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/CanonicalClassNameUsageTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreMatchersTest.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsEmpty.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsIdentityOperation.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsRefasterAsVarargs.java
Labels: new feature

#880 Introduce `UnqualifiedSuggestedFixImport` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CollectorMutability.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitValueSource.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MethodReferenceUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/PrimitiveComparison.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/SpringMvcAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/UnqualifiedSuggestedFixImport.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/UnqualifiedSuggestedFixImportTest.java
Labels: new feature

#922 Disallow static import of `com.google.errorprone.{VisitorState,util.ASTHelpers}` members
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
Labels: improvement

#882 Introduce ErrorProneRuntimeClasspath check
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/BugPatternTestExtractor.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CollectorMutability.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/EmptyMethod.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ErrorProneRuntimeClasspath.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxImplicitBlock.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitValueSource.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestMappingAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibrary.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ErrorProneRuntimeClasspathTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreTypesTest.java
Labels: new feature

#927 Update Error Prone `-XepExcludedPaths` flag to be Windows-compatible
  pom.xml
Labels: chore
