Repository PicnicSupermarket/error-prone-support, pull requests merged in 2023-04, with the labels that each got.

#563 Introduce `MonoJustOrEmptyOptional` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#571 Introduce `FluxCollectToImmutableSet` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#570 Introduce `FluxCollectToImmutableList` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#572 Improve contribution documentation
  CONTRIBUTING.md
  README.md
  SECURITY.md
  run-full-build.sh
Labels: documentation

#562 Apply assorted test cleanup
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversionTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/JavaKeywordsTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MethodMatcherFactoryTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibraryTest.java
Labels: improvement

#581 Fix and enable `SuggestedFixRules` tests
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/SuggestedFixRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/SuggestedFixRulesTestOutput.java
Labels: documentation

#568 Have `DirectReturn` check consider `finally` blocks
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/DirectReturn.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/DirectReturnTest.java
Labels: improvement

#573 Introduce CodeQL security vulnerability analysis
  .github/workflows/codeql.yml
Labels: chore

#574 Introduce OpenSSF Scorecard GitHub action
  .github/workflows/build.yaml
  .github/workflows/deploy-website.yaml
  .github/workflows/openssf-scorecard.yml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
Labels: chore

#576 Introduce `AssertThatMapContainsOnlyKeys` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJMapRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestOutput.java
Labels: new feature

#577 Introduce `StringIs{,Not}EmptyPredicate` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestOutput.java
Labels: new feature

#560 Introduce `AssociativeMethodInvocation` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AssociativeMethodInvocation.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/AssociativeMethodInvocationTest.java
Labels: new feature

#584 Add additional quality badges to README
  README.md
Labels: documentation

#593 Extend `StreamRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: new feature
