Repository PicnicSupermarket/error-prone-support, pull requests merged in 2023-08, with the labels that each got.

#738 Fix typos in `CanonicalSyntaxAnnotation.java`
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalAnnotationSyntax.java
Labels: documentation

#727 StreamsTakeWhileFilter & FluxTakeWhileFilter
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/DoubleStreamRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/IntStreamRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/LongStreamRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/DoubleStreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/DoubleStreamRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/IntStreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/IntStreamRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/LongStreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/LongStreamRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: new feature

#642 Introduce `NestedPublishers` bug check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NestedOptionals.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NestedPublishers.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreMatchers.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreTypePredicates.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/NestedOptionalsTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/NestedPublishersTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreMatchersTest.java
Labels: new feature

#617 Introduce `VerifyOnlyElementInFlux` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#745 Have Renovate file GitHub CodeQL upgrade PRs once every four weeks
  .renovaterc.json
Labels: chore

#757 Introduce mutation test script for changed code
  CONTRIBUTING.md
  README.md
  run-branch-mutation-tests.sh
  run-mutation-tests.sh
Labels: chore

#762 Introduce `StreamIterate` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: new feature

#767 Introduce `FileRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestOutput.java
Labels: new feature

#766 Introduce `CollectionContains` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Labels: new feature
