Repository PicnicSupermarket/error-prone-support, pull requests merged in 2023-02, with the labels that each got.

#493 Update `.mvn/maven.config` for compatibility with Maven 3.9.0
  .mvn/maven.config
Labels: chore

#428 Introduce `documentation-support` module
  documentation-support/pom.xml
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/BugPatternExtractor.java
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/DocumentationGenerator.java
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListener.java
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/Extractor.java
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/ExtractorType.java
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/package-info.java
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/BugPatternExtractorTest.java
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/Compilation.java
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListenerTest.java
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTest.java
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/bugpattern-documentation-complete.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/bugpattern-documentation-minimal.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/bugpattern-documentation-undocumented-suppression.json
  error-prone-contrib/pom.xml
  pom.xml
Labels: documentation

#430 Add Gradle installation instructions to README
  README.md
Labels: documentation

#498 Upgrade Maven API 3.8.6 -> 3.8.7
  pom.xml
Labels: dependencies

#472 Introduce `FluxImplicitBlock` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxImplicitBlock.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/FluxImplicitBlockTest.java
Labels: new feature

#497 Introduce `StreamMapTo{Double,Int,Long}Sum` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsLambdaExpressionOrMethodReference.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/IsLambdaExpressionOrMethodReferenceTest.java
Labels: new feature
