Repository PicnicSupermarket/error-prone-support, pull requests merged in 2023-05, with the labels that each got.

#606 Fix Gradle installation guide link in README
  README.md
Labels: documentation

#604 Upgrade JDKs used by GitHub Actions builds
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yaml
  .github/workflows/codeql.yml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
  .github/workflows/sonarcloud.yml
Labels: dependencies

#609 Extend `AssertJThrowingCallableRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestOutput.java
Labels: new feature

#608 Extend `PrimitiveRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PrimitiveRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestOutput.java
Labels: new feature

#607 Prefer Sets#intersection over more contrived alternatives.
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableSetRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableSetRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableSetRulesTestOutput.java
Labels: new feature

#605 Extend `StreamRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: new feature

#623 Introduce `IsRefasterAsVarargs` matcher
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsRefasterAsVarargs.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/IsRefasterAsVarargsTest.java
Labels: new feature

#619 Introduce `StreamsConcat` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: new feature

#627 Make `ThirdPartyLibrary` compatible with `-source 8`
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibrary.java
Labels: bug fix

#599 Improve `AbstractMatcherTestChecker`
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/AbstractMatcherTestChecker.java
Labels: improvement

#527 Rewrite `Optional#orElse` to `Optional#orElseGet` for non-constant expressions
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsLikelyTrivialComputation.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/IsLikelyTrivialComputationTest.java
Labels: new feature
