Repository PicnicSupermarket/error-prone-support, pull requests merged in 2023-10, with the labels that each got.

#774 Disallow `autovalue.shaded.*` imports
  pom.xml
Labels: chore

#780 Upgrade JDKs used by GitHub Actions builds
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yaml
  .github/workflows/codeql.yml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
  .github/workflows/sonarcloud.yml
Labels: chore

#763 Introduce assorted Reactor Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#813 Add another variant to the `StepVerifierLastStepVerifyErrorClass`
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#811 Introduce `ClassRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ClassRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestOutput.java
Labels: new feature

#777 Introduce additional Mockito Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MockitoRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MockitoRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MockitoRulesTestOutput.java
Labels: new feature

#815 Introduce `FluxEmpty` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#810 Introduce `{Mono,Flux}OfType` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#826 Enable test for `ClassRules` rule collection
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestOutput.java
Labels: chore

#771 Introduce `PatternRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PatternRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/AmbiguousJsonCreatorTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/FluxImplicitBlockTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StringJoinTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PatternRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PatternRulesTestOutput.java
  refaster-runner/src/test/java/tech/picnic/errorprone/refaster/runner/RefasterTest.java
Labels: new feature

#814 Introduce `ImmutableList.of().stream()` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: new feature

#832 Build and test against JDK 21 instead of JDK 20
  .github/workflows/build.yaml
Labels: chore

#812 Introduce assorted `BigDecimal#signum` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/BigDecimalRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BigDecimalRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BigDecimalRulesTestOutput.java
Labels: new feature

#822 Introduce `{Integer,Long}SignumIs{Positive,Negative}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PrimitiveRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestOutput.java
Labels: new feature

#744 Introduce `IsEmpty` matcher for use by Refaster templates
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJMapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
  refaster-support/pom.xml
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsEmpty.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/IsEmptyTest.java
Labels: new feature

#817 Introduce `JUnitParameterizedMethodDeclaration` bug checker
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AutowiredConstructor.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitNullaryParameterizedTestDeclaration.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/JUnitNullaryParameterizedTestDeclarationTest.java
Labels: new feature

#749 Introduce `IsIdentityOperation` matcher for use by Refaster templates
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableListMultimapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableListMultimapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableListMultimapRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMapRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsIdentityOperation.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/IsIdentityOperationTest.java
Labels: new feature

#450 Introduce BugPattern for disallowing specified static imports
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/NonStaticImportTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StaticImportTest.java
Labels: new feature

#865 Introduce Checkstyle integration test
  .github/workflows/run-integration-tests.yml
  .gitignore
  integration-tests/checkstyle-10.12.4-expected-changes.patch
  integration-tests/checkstyle-10.12.4-expected-warnings.txt
  integration-tests/checkstyle-10.12.4-init.patch
  integration-tests/checkstyle-10.12.4.sh
Labels: improvement

#862 Disallow static import of `BugCheckerRefasctoringTestHelper.TestMode#TEXT_MATCH`
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
  refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/RefasterRuleCollection.java
Labels: improvement
