Repository PicnicSupermarket/error-prone-support, pull requests merged in 2024-12, with the labels that each got.

#1442 Drop the `JavaKeywords` class
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/ConflictDetection.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/JavaKeywords.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/SourceCode.java
  error-prone-utils/src/test/java/tech/picnic/errorprone/utils/JavaKeywordsTest.java
  error-prone-utils/src/test/java/tech/picnic/errorprone/utils/SourceCodeTest.java
Labels: chore

#1423 Introduce `PublisherProbeAssertWas{,Not}{Subscribed,Cancelled,Requested}` Refaster rules
  README.md
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#1455 Make integration tests Error Prone 2.36.0-compatible
  integration-tests/checkstyle-init.patch
  integration-tests/metrics-init.patch
Labels: chore

#985 Introduce `ExplicitArgumentEnumeration` check
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitArgumentEnumeration.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ExplicitArgumentEnumerationTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListingTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversionTest.java
  pom.xml
Labels: new feature

#1449 Ignore type variable casts in `ClassCastLambdaUsage` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ClassCastLambdaUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ClassCastLambdaUsageTest.java
Labels: bug fix

#1471 Introduce `AssertThatThrownBy*ExceptionRootCauseHasMessage` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestOutput.java
Labels: new feature

#1476 Improve `JUnitMethodDeclaration` method rename heuristics
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/JUnitMethodDeclarationTest.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/ConflictDetection.java
  error-prone-utils/src/test/java/tech/picnic/errorprone/utils/ConflictDetectionTest.java
Labels: improvement

#1467 Introduce `StreamMapFilter` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: new feature

#1477 Generalize `AssertThatThrownBy` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestOutput.java
Labels: improvement

#1468 Introduce Prometheus Java Client integration test
  .github/workflows/run-integration-tests.yml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitMethodDeclaration.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java
  integration-tests/prometheus-java-client-expected-changes.patch
  integration-tests/prometheus-java-client-expected-warnings.txt
  integration-tests/prometheus-java-client-init.patch
  integration-tests/prometheus-java-client.sh
Labels: chore

#1479 Introduce `AssertThatString{Contains,DoesNotContain}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJStringRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestOutput.java
Labels: new feature

#1480 Introduce `CharSequenceRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CharSequenceRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CharSequenceRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CharSequenceRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestOutput.java
Labels: new feature

#46 Update comments referencing Refaster rule limitation
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableListMultimapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableListRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMultisetRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableSetMultimapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableSetRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableSortedMapRules.java
Labels: chore

#1482 Sync Dropwizard Metrics integration test
  integration-tests/metrics-expected-changes.patch
Labels: chore

#1490 Run GitHub Actions workflows on `macos-15` and `windows-2025`
  .github/workflows/build.yml
Labels: chore

#1494 Extend `{Is,Non}NullFunction` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/NullRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestOutput.java
Labels: new feature
