Repository PicnicSupermarket/error-prone-support, pull requests merged in 2024-03, with the labels that each got.

#733 Introduce `EmptyMonoZip` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/EmptyMonoZip.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/EmptyMonoZipTest.java
Labels: good first issue, new feature

#1056 Exempt `picocli.CommandLine.Option#names` annotation attribute from reordering
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
Labels: improvement

#1060 Exclude `error-prone-{experimental,guidelines}` checks from integration tests
  integration-tests/checkstyle.sh
Labels: chore

#1064 Sync Checkstyle integration test
  integration-tests/checkstyle-expected-changes.patch
  integration-tests/checkstyle-expected-warnings.txt
  integration-tests/checkstyle-init.patch
  integration-tests/checkstyle.sh
Labels: chore

#1076 Have `step-security/harden-runner` audit the OpenSSF Scorecard update workflow
  .github/workflows/openssf-scorecard.yml
Labels: chore

#1084 Drop unused field in `Slf4jLogStatementTest`
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatementTest.java
Labels: chore

#1028 Compact and replace `StreamIs{,Not}Empty` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: improvement

#1024 Introduce `OptionalOrElse` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/OptionalOrElse.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/OptionalOrElseTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java
  integration-tests/checkstyle-expected-changes.patch
  refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java
Labels: new feature

#1105 Start release notes with "Update considerations and deprecations" section
  .github/release.yml
Labels: chore

#1104 Introduce Refaster rules that resolve `EnumOrdinal` violations
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/EqualityRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestOutput.java
Labels: new feature

#1075 Introduce Cody as IntelliJ icon
  .gitignore
  .idea/icon.svg
Labels: chore
