Repository PicnicSupermarket/error-prone-support, pull requests merged in 2024-11, with the labels that each got.

#1387 Fix `error-prone-contrib` runtime classpath
  error-prone-contrib/pom.xml
Labels: bug fix

#1392 Upgrade ruby/setup-ruby v1.174.0 -> v1.199.0
  .github/workflows/deploy-website.yml
Labels: dependencies

#1391 Run GitHub Actions workflows on `ubuntu-24.04`
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/deploy-website.yml
  .github/workflows/openssf-scorecard.yml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
  .github/workflows/run-integration-tests.yml
  .github/workflows/sonarcloud.yml
Labels: chore

#1406 Update Error Prone compatibility matrix
  website/_data/compatibility.yml
Labels: documentation

#1410 Track `StreamFlatMapOptional` Refaster rule caveat
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java
Labels: chore

#1412 Update `step-security/harden-runner` configuration
  .github/workflows/openssf-scorecard.yml
Labels: chore

#1395 Introduce `Instant{Identity,TruncatedTo{Milliseconds,Seconds}}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TimeRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/IdentityConversionTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TimeRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TimeRulesTestOutput.java
Labels: new feature

#1132 Introduce assorted Reactor `StepVerifier` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#1413 Replace deprecated `build-helper:remove-project-artifact` goal
  .github/workflows/build.yml
  .github/workflows/run-integration-tests.yml
  pom.xml
Labels: chore

#1424 Update Checkstyle integration test
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java
  integration-tests/checkstyle-expected-changes.patch
  integration-tests/checkstyle-init.patch
  integration-tests/checkstyle.sh
  integration-tests/run-integration-test.sh
Labels: chore

#1425 Upgrade Checkstyle integration test target 10.14.0 -> 10.21.1
  integration-tests/checkstyle-expected-changes.patch
  integration-tests/checkstyle-expected-warnings.txt
  integration-tests/checkstyle-init.patch
  integration-tests/checkstyle.sh
Labels: chore

#1138 Introduce `RedundantStringEscape` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringEscape.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatement.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/BugCheckerRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RedundantStringEscapeTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BugCheckerRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BugCheckerRulesTestOutput.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/BugPatternLink.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ErrorProneRuntimeClasspath.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ExhaustiveRefasterTypeMigration.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/SourceCode.java
  error-prone-utils/src/test/java/tech/picnic/errorprone/utils/SourceCodeTest.java
Labels: new feature

#1436 Fix `Slf4jLoggerDeclaration` flag name
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLoggerDeclaration.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/Slf4jLoggerDeclarationTest.java
Labels: improvement

#1426 Introduce Dropwizard Metrics integration test
  .github/workflows/run-integration-tests.yml
  integration-tests/checkstyle.sh
  integration-tests/metrics-expected-changes.patch
  integration-tests/metrics-expected-warnings.txt
  integration-tests/metrics-init.patch
  integration-tests/metrics.sh
  integration-tests/run-integration-test.sh
Labels: chore
