Repository PicnicSupermarket/error-prone-support, pull requests merged in 2024-01, with the labels that each got.

#914 Have `ThrowsCheckedException` also consider supertypes
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/ThrowsCheckedException.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/ThrowsCheckedExceptionTest.java
Labels: bug fix

#939 Prevent likely static import class with `FailWithMessage{,AndThrowable}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JUnitToAssertJRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JUnitToAssertJRulesTestOutput.java
Labels: improvement

#925 Add `rewrite-templating` annotation processor to also produce OpenRewrite recipes
  error-prone-contrib/pom.xml
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/StringRulesRecipesTest.java
  pom.xml
  refaster-runner/pom.xml
  refaster-test-support/pom.xml
Labels: new feature

#951 Extend `OptionalIdentity` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java
Labels: new feature

#956 Show original Cody in README and on website home page
  website/assets/images/logo-dark.svg
  website/assets/images/logo.svg
Labels: documentation

#955 Update year to 2024 in `footer_custom.html` and `LICENSE.md`
  LICENSE.md
  website/_includes/footer_custom.html
Labels: chore

#937 Make `BugPattern{,Test}Extractor` tests more maintainable
  documentation-support/pom.xml
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/BugPatternExtractor.java
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/BugPatternTestExtractor.java
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListener.java
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/Json.java
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/BugPatternExtractorTest.java
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest.java
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/JsonTest.java
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternExtractorTest-bugpattern-CompleteBugChecker.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternExtractorTest-bugpattern-MinimalBugChecker.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternExtractorTest-bugpattern-UndocumentedSuppressionBugPattern.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest-bugpattern-test-CompilationAndBugCheckerRefactoringTestHelpersTest.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest-bugpattern-test-CompilationAndBugCheckerRefactoringTestHelpersWithCustomCheckerPackageAndNamesTest.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest-bugpattern-test-MultiFileBugCheckerRefactoringTestHelperTest.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest-bugpattern-test-MultiFileCompilationTestHelperTest.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest-bugpattern-test-SingleFileBugCheckerRefactoringTestHelperTest.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest-bugpattern-test-SingleFileBugCheckerRefactoringTestHelperWithSetArgsFixChooserAndCustomTestModeTest.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest-bugpattern-test-SingleFileCompilationTestHelperTest.json
  documentation-support/src/test/resources/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest-bugpattern-test-SingleFileCompilationTestHelperWithSetArgsTest.json
Labels: chore

#958 Work around IntelliJ IDEA bug IDEA-342187
  error-prone-contrib/pom.xml
  pom.xml
  refaster-runner/pom.xml
  refaster-test-support/pom.xml
Labels: chore

#775 Introduce `RefasterMethodParameterOrder` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RefasterMethodParameterOrder.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/EqualityRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableListRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JUnitToAssertJRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RefasterMethodParameterOrderTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestOutput.java
Labels: do not merge, new feature

#964 Build with Maven 3.9.6
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
  .github/workflows/run-integration-tests.yml
  .github/workflows/sonarcloud.yml
Labels: chore

#491 Run `org.kordamp.maven:pomchecker-maven-plugin:1.10.0:check-maven-central`
  documentation-support/pom.xml
  error-prone-contrib/pom.xml
  pom.xml
  refaster-compiler/pom.xml
  refaster-runner/pom.xml
  refaster-support/pom.xml
  refaster-test-support/pom.xml
Labels: chore

#974 Drop workaround for resolved Refaster bug
  refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java
Labels: improvement

#973 Drop unnecessary dependency declarations
  documentation-support/pom.xml
  error-prone-contrib/pom.xml
  refaster-runner/pom.xml
  refaster-support/pom.xml
  refaster-test-support/pom.xml
Labels: chore

#976 Fix the mutation test setup
  documentation-support/pom.xml
  error-prone-contrib/pom.xml
  refaster-runner/pom.xml
  refaster-support/pom.xml
  refaster-test-support/pom.xml
Labels: chore

#963 Introduce `InputStreamRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/InputStreamRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/InputStreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/InputStreamRulesTestOutput.java
Labels: new feature

#971 Introduce additional `Multimap` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MultimapRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MultimapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MultimapRulesTestOutput.java
Labels: new feature

#970 Introduce `{Max,Min}ByNaturalOrder` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java
Labels: new feature

#978 Avoid NPE in `IsEmpty` matcher
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsEmpty.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/IsEmptyTest.java
Labels: bug fix

#969 Introduce additional Reactor Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#938 Publish Error Prone compatibility matrix on website
  website/_config.yml
  website/_data/compatibility.yml
  website/compatibility.md
  website/generate-version-compatibility-overview.sh
Labels: documentation

#986 Actually skip test failures during SonarCloud analysis
  pom.xml
Labels: bug fix

#998 Prevent `ExplicitEnumOrdering` from throwing an NPE
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrdering.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrderingTest.java
Labels: bug fix

#996 Allow static imports of `{ZERO,ONE}` identifiers
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/NonStaticImportTest.java
Labels: improvement

#999 Sync Checkstyle integration test
  .github/workflows/run-integration-tests.yml
  integration-tests/checkstyle-expected-changes.patch
  integration-tests/checkstyle-expected-warnings.txt
  integration-tests/checkstyle-init.patch
  integration-tests/checkstyle.sh
Labels: chore

#1011 Run builds on macOS 14 rather than macOS 12
  .github/workflows/build.yml
Labels: chore

#979 Use `plus###` and `minus###` shorthands when possible for dates/times
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TimeRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TimeRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TimeRulesTestOutput.java
Labels: new feature
