Repository PicnicSupermarket/error-prone-support, pull requests merged in 2024-08, with the labels that each got.

#1271 Update `step-security/harden-runner` configuration
  .github/workflows/openssf-scorecard.yml
  .github/workflows/sonarcloud.yml
Labels: chore

#1264 Introduce `SetStream` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Labels: new feature

#1261 Introduce `FluxFromStreamSupplier` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#1162 Introduce `FilesCreateTempFileToFile` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestOutput.java
Labels: new feature

#1141 Introduce generic `run-integration-test.sh` script
  integration-tests/checkstyle.sh
  integration-tests/run-integration-test.sh
Labels: chore

#1270 Package OpenRewrite recipes in separate JAR, targeting Java 8
  pom.xml
Labels: improvement

#1275 Introduce `ArraysAsList` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Labels: new feature

#1277 Make the build JDK 22-compatible
  .github/workflows/build.yml
  refaster-compiler/src/main/java/tech/picnic/errorprone/refaster/plugin/RefasterRuleCompilerTaskListener.java
Labels: improvement

#1269 Introduce `Class{Literal,Reference}Cast` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ClassRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestOutput.java
Labels: new feature

#1281 Update Error Prone compatibility matrix
  website/_data/compatibility.yml
Labels: documentation

#1282 Introduce additional `File` and `Path` Refaster rules
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListener.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestOutput.java
Labels: new feature

#1276 Introduce `{Max,Min}Of{Array,Collection}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java
Labels: new feature

#1290 Introduce `MonoFromFutureAsyncLoadingCacheGet` Refaster rule
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
  pom.xml
Labels: new feature
