Repository PicnicSupermarket/error-prone-support, pull requests merged in 2024-02, with the labels that each got.

#992 Disallow static import of `{Mono,Flux}` and partially allow `empty`
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/NonStaticImportTest.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StaticImportTest.java
Labels: improvement

#867 Make Checkstyle integration test macOS-compatible
  integration-tests/checkstyle.sh
Labels: chore

#1003 Introduce `error-prone-experimental` module
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IsInstanceLambdaUsage.java
  error-prone-experimental/README.md
  error-prone-experimental/pom.xml
  error-prone-experimental/src/main/java/tech/picnic/errorprone/experimental/bugpatterns/MethodReferenceUsage.java
  error-prone-experimental/src/test/java/tech/picnic/errorprone/experimental/bugpatterns/MethodReferenceUsageTest.java
  pom.xml
Labels: improvement

#1002 Introduce `error-prone-guidelines` module
  error-prone-contrib/pom.xml
  error-prone-guidelines/README.md
  error-prone-guidelines/pom.xml
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/AssociativeMethodInvocation.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ErrorProneRuntimeClasspath.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ErrorProneTestHelperSourceFormat.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/RefasterAnyOfUsage.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/RefasterMethodParameterOrder.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/RefasterRuleModifiers.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/UnqualifiedSuggestedFixImport.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/package-info.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/AssociativeMethodInvocationTest.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/ErrorProneRuntimeClasspathTest.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/ErrorProneTestHelperSourceFormatTest.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/RefasterAnyOfUsageTest.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/RefasterMethodParameterOrderTest.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/RefasterRuleModifiersTest.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/UnqualifiedSuggestedFixImportTest.java
  pom.xml
Labels: improvement

#1023 Introduce `package-info.java` for `tech.picnic.errorprone.guidelines.bugpatterns`
  error-prone-experimental/pom.xml
  error-prone-experimental/src/main/java/tech/picnic/errorprone/experimental/bugpatterns/package-info.java
Labels: chore

#1025 Extend `StreamIsEmpty` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Labels: new feature

#1012 Introduce `NewStringFromCharArray{,SubSequence}` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestOutput.java
Labels: new feature

#770 Introduce `ExhaustiveRefasterTypeMigration` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JUnitToAssertJRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java
  error-prone-guidelines/pom.xml
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ExhaustiveRefasterTypeMigration.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/ExhaustiveRefasterTypeMigrationTest.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/annotation/TypeMigration.java
Labels: new feature

#603 Require JDK 17 rather than JDK 11
  .github/workflows/build.yml
  README.md
  documentation-support/src/main/java/tech/picnic/errorprone/documentation/BugPatternTestExtractor.java
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListenerTest.java
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AmbiguousJsonCreator.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalAnnotationSyntax.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalClassNameUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/DirectReturn.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ImmutablesSortedSetComparator.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IsInstanceLambdaUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitValueSource.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MockitoMockClassReference.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MongoDBTextFilterUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NestedPublishers.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/PrimitiveComparison.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestMappingAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestParamType.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/SpringMvcAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsage.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java
  error-prone-experimental/src/main/java/tech/picnic/errorprone/experimental/bugpatterns/MethodReferenceUsage.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ErrorProneRuntimeClasspath.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ExhaustiveRefasterTypeMigration.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/RefasterAnyOfUsage.java
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/UnqualifiedSuggestedFixImport.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/AnnotationAttributeMatcher.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/MoreJUnitMatchers.java
  pom.xml
  refaster-compiler/src/main/java/tech/picnic/errorprone/refaster/plugin/RefasterRuleCompiler.java
  refaster-runner/pom.xml
  refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java
  refaster-runner/src/test/java/tech/picnic/errorprone/refaster/runner/RefasterTest.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsEmpty.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsLikelyTrivialComputation.java
  refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/ThrowsCheckedException.java
  refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/AbstractMatcherTestChecker.java
  refaster-test-support/pom.xml
  refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/RefasterRuleCollection.java
Labels: breaking change

#1029 Re-enable SonarCloud analysis on default branch
  .github/workflows/sonarcloud.yml
Labels: chore

#1026 Introduce `BugPatternLink` check
  error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/BugPatternLink.java
  error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/BugPatternLinkTest.java
  refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/RefasterRuleCollection.java
Labels: new feature

#993 Introduce `InputStream{Read,Skip}NBytes` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/InputStreamRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/InputStreamRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/InputStreamRulesTestOutput.java
Labels: new feature

#1027 Extend `CollectionIsEmpty` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Labels: new feature

#1043 Upgrade JDKs used by GitHub Actions builds
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
  .github/workflows/run-integration-tests.yml
  .github/workflows/sonarcloud.yml
Labels: chore

#1046 Have Renovate file `action-download-artifact` PRs once every four weeks
  .renovaterc.json
Labels: chore

#1047 Introduce `FluxFromIterable` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature
