Repository PicnicSupermarket/error-prone-support, pull requests merged in 2024-10, with the labels that each got.

#1347 Extend `ImmutableCollectionIterator` refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Labels: improvement

#1358 Update Error Prone compatibility matrix
  website/_data/compatibility.yml
Labels: documentation

#1302 Introduce `ImmutableEnumSetRules` Refaster rule collection
  documentation-support/src/test/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListenerTest.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitClassModifiers.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssortedRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableEnumSetRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssortedRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssortedRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableEnumSetRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableEnumSetRulesTestOutput.java
Labels: new feature

#1365 Introduce `MicrometerRules` Refaster rule collection
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MicrometerRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MicrometerRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MicrometerRulesTestOutput.java
  pom.xml
Labels: new feature

#1378 Use dynamic Reproducible Builds badge
  README.md
Labels: chore

#794 Introduce `ConstantNaming` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ConstantNaming.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestParamType.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ConstantNamingTest.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/Flags.java
  error-prone-utils/src/test/java/tech/picnic/errorprone/utils/FlagsTest.java
Labels: new feature

#783 Introduce `Slf4jLoggerDeclaration` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/EmptyMethod.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLoggerDeclaration.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/Slf4jLoggerDeclarationTest.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/MoreASTHelpers.java
  error-prone-utils/src/test/java/tech/picnic/errorprone/utils/MoreASTHelpersTest.java
Labels: new feature

#1329 Upgrade JDKs used by GitHub Actions builds
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/pitest-analyze-pr.yml
  .github/workflows/pitest-update-pr.yml
  .github/workflows/run-integration-tests.yml
  .github/workflows/sonarcloud.yml
  pom.xml
  website/generate-version-compatibility-overview.sh
Labels: chore

#1379 Introduce `NameContentEquals` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ConstantNaming.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/BugCheckerRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BugCheckerRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BugCheckerRulesTestOutput.java
Labels: new feature

#1385 Ignore primitive casts in `ClassCastLambdaUsage` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ClassCastLambdaUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ClassCastLambdaUsageTest.java
Labels: bug fix
