Repository PicnicSupermarket/error-prone-support, pull requests merged in 2025-05, with the labels that each got.

#1651 Validate compatibility with latest Error Prone release
  .github/workflows/error-prone-compat.yml
  .github/workflows/sonarcloud.yml
  run-full-build.sh
Labels: chore

#1662 Introduce `JacksonRules` Refaster rule collection
  error-prone-contrib/pom.xml
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JacksonRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JacksonRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JacksonRulesTestOutput.java
Labels: new feature

#1664 Extend `AssertJMapRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJMapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestOutput.java
Labels: improvement

#1669 Fix integration test setup
  .github/workflows/run-integration-tests.yml
  integration-tests/checkstyle-expected-changes.patch
  integration-tests/checkstyle-init.patch
Labels: chore

#1683 Update `step-security/harden-runner` configuration
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/pitest-analyze-pr.yml
Labels: chore

#1660 Introduce Reviewdog
  .github/workflows/reviewdog.yml
  .reviewdog.yml
  pom.xml
Labels: chore

#1701 Run integration tests also on push to `master`
  .github/workflows/integration-tests.yml
Labels: chore

#1696 Upgrade `prometheus-java-client` integration test target 1.3.5 -> 1.3.8
  integration-tests/prometheus-java-client-expected-changes.patch
  integration-tests/prometheus-java-client-expected-warnings.txt
  integration-tests/prometheus-java-client-init.patch
  integration-tests/prometheus-java-client.sh
Labels: chore

#1695 Drop obsolete SPR-13984 workaround
  pom.xml
Labels: chore
