Repository PicnicSupermarket/error-prone-support, pull requests merged in 2025-04, with the labels that each got.

#1637 Avoid invalid `ExplicitArgumentEnumeration` suggestions
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitArgumentEnumeration.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ExplicitArgumentEnumerationTest.java
Labels: bug fix

#1642 Update Error Prone compatibility matrix
  website/_data/compatibility.yml
Labels: chore

#1650 Drop unmaintained `reactor-error-prone` dependency
  .github/workflows/build.yml
  .github/workflows/deploy-website.yml
  pom.xml
  run-full-build.sh
  settings.xml
Labels: chore

#1649 Upgrade Error Prone 2.37.0 -> 2.38.0
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java
  pom.xml
Labels: dependencies

#1648 Drop IDEA-342187 workaround
  error-prone-contrib/pom.xml
  error-prone-guidelines/pom.xml
  pom.xml
  refaster-runner/pom.xml
  refaster-test-support/pom.xml
Labels: chore

#1645 Share same generic parameters with the templates
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TestNGToAssertJRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TestNGToAssertJRulesTestOutput.java
Labels: improvement
