Repository PicnicSupermarket/error-prone-support, pull requests merged in 2025-01, with the labels that each got.

#1481 Generalize assorted Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJCharSequenceRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJMapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJStringRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssortedRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJCharSequenceRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJCharSequenceRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Labels: improvement

#1483 Extend `TestNGToAssertJRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TestNGToAssertJRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TestNGToAssertJRulesTestOutput.java
Labels: new feature

#1493 Introduce `FluxMapNotNull{,Transformation}OrElse` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#1489 Introduce `ImmutableTableRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitArgumentEnumeration.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableTableRules.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableTableRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableTableRulesTestOutput.java
Labels: new feature

#1488 Extend `ImmutableMapRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/SpringMvcAnnotation.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableSortedMapRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMapRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMapRulesTestOutput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableSortedMapRulesTestInput.java
  integration-tests/checkstyle-expected-changes.patch
  integration-tests/prometheus-java-client-expected-changes.patch
Labels: new feature

#1484 Extend `JUnitToAssertJRules` Refaster rule collection
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JUnitToAssertJRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JUnitToAssertJRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JUnitToAssertJRulesTestOutput.java
Labels: new feature

#1500 Make Mockito setup IntelliJ IDEA-compatible
  README.md
  pom.xml
Labels: chore

#1499 Upgrade Error Prone fork 2.36.0-picnic-1 -> 2.36.0-picnic-2
  .github/workflows/build.yml
  .github/workflows/deploy-website.yml
  README.md
  documentation-support/pom.xml
  error-prone-contrib/pom.xml
  error-prone-experimental/pom.xml
  error-prone-guidelines/pom.xml
  error-prone-utils/pom.xml
  pom.xml
  refaster-compiler/pom.xml
  refaster-runner/pom.xml
  refaster-support/pom.xml
  refaster-test-support/pom.xml
  settings.xml
  website/generate-version-compatibility-overview.sh
Labels: dependencies, chore

#1139 Introduce `EagerStringFormatting` check
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/EagerStringFormatting.java
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatement.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/EagerStringFormattingTest.java
  error-prone-utils/src/main/java/tech/picnic/errorprone/utils/SourceCode.java
  integration-tests/checkstyle-expected-changes.patch
  integration-tests/checkstyle-expected-warnings.txt
  integration-tests/prometheus-java-client-expected-changes.patch
Labels: new feature

#1507 Have `TimeZoneUsage` check also flag illegal method references
  error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsage.java
  error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsageTest.java
Labels: improvement
