Repository PicnicSupermarket/error-prone-support, pull requests merged in 2025-03, with the labels that each got.

#1591 Upgrade Error Prone fork 2.36.0-picnic-2 -> 2.36.0-picnic-4
  pom.xml
Labels: dependencies

#1586 Upgrade Arcmutate plugins
  pom.xml
Labels: dependencies

#1596 Introduce two `FileRules` Refaster rules
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestOutput.java
Labels: new feature

#1581 Extend `FluxJust` Refaster rule
  error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java
  error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Labels: new feature

#1613 Update Error Prone compatibility matrix
  website/_data/compatibility.yml
Labels: chore
